### PR TITLE
v1.0.0 Boards Manager install support

### PR DESCRIPTION
**Pull request by per1234**
Boards Manager URL for testing: 
https://raw.githubusercontent.com/per1234/MiniCore/bmtest/package_MCUdude_MiniCore_index.json

clipboard01

### CODE REVIEW

**Comment by MCUdude** [comment]
Wow, that was quick! Is it possible to list this core on the [Arduino on other Atmel chips](http://playground.arduino.cc/Main/ArduinoOnOtherAtmelChips) and the [Unofficial list of 3rd party board links](https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls)?

**Comment by per1234** [comment]
Sure, will do.

**Comment by MCUdude** [comment]
Have a look at [line 20](https://github.com/MCUdude/MiniCore/pull/2/files#diff-308aae0e86d7105a9cf8dec8e88141d9R20). Wouldn't this use the ink in your fork rather than this fork?

**Comment by per1234** [comment]
Oops, that got mixed up with my test file somehow. I've fixed it and done a force push so there's only one commit.

**Comment by MCUdude** [comment]
Awesome, thank you for all your help! 
I hope people find this core useful. At least I do 😉

**Comment by per1234** [comment]
I've added MiniCore to the Playground and Unofficial list of 3rd party boards support urls wiki

**Pull request merged**
