### PR TITLE
Define Wire2 with using TwoWire class

### PR DESCRIPTION
**Pull request by asukiaaa**
I checked that this code can run double I2C slave bus.

### CODE REVIEW

**Comment by asukiaaa** [comment]
I defined Wire and Wire2 in Wire.h with sharing TwoWire and Twi class.
The change reduces memory usage.
Please check it.

**Comment by MCUdude** [comment]
Sorry, I have been busy with other things recently.

> The change reduced RAM usage but increased flash usage.

A slight increase in flash usage for devices that has a second TWI interface would be OK I think. The downside with your last commit is that it increases the flash usage in all devices, including devices that don't have a second TWI interface

Here's a comparison when compiling the i2cScanner.ino sketch.

|                           | master branch | feature/define-wire2-with-using-twowire |
|----------------|---------------|-----------------------------------------|
| ATmega328P   | 3618B / 514B   | 5398B / 398B |
| ATmega328PB | 3826B / 514B  | 5820B / 464B |
| ATmega48P     | 4008B / 422B  | **5190B** / 320B | 

Even though it's very convenient to have one Wire library for everything, this will be seen as setback for most users, since the ATmega328PB isn't very popular compared to the other chips MiniCore supports.

**Comment by asukiaaa** [comment]
So, do you want to keep code on master branch?

**Comment by asukiaaa** [comment]
How about the updated code that switches Wire_multiple and Wire_single by presence of TWI1_vect.
The code can keep same resource usage for single I2C bus MCU and define Wire1 with using TwoWire class for double I2C bus MCU.
However similar code is avairable on Wire_* and twi_* files.

**Comment by asukiaaa** [comment]
I found that this code does not work when Wire works as slave and Wire1 works as master. (Master branch works even if that state.)
I seek the difference.

**Comment by asukiaaa** [comment]
@MCUdude 
I update code to activate customizable TwoWire if TWI1_vect is defined.
This code does not increase usage for single wire MCU.
I checked that this program works on the following settings on ATmega328PB.

- Double slave
- Wire as slave and Wire1 as master

Could you give me some feedback?

**Comment by asukiaaa** [comment]
I forse pushed new commit to this branch so if you try this code on local, please delete old branch and pull again.

**Comment by MCUdude** [comment]
I just tested your code. This looks **very** promising!

Formatting wise: some of the files are missing a newline at the end. Could you add this? Also, the header is Wire.h, Wire.cpp, Wire1.h and Wire1.cpp are referring to TwoWire.h/cpp. Could you edit this to reflext the actual names? This is BTW not your fault 😉

The only downside I've found is that the compiled size for ATmega328PB is larger than it was when only one i2c port is in use.
For the i2c_scanner sketch, before it compiled to 4412 bytes, but with your library it compiles to 5764 bytes. It would be incredible if it was possible to fix this, but I can tell you, I'm not competent enough to do that.

It's also very nice that twi.h/c and twi1.h/c isn't touched anymore. The code in these files are very proven, and I'm more confident now that this PR is more about getting Wire and Wire1 into the same class.

**Comment by MCUdude** [comment]
I'll do some testing on an Atmega328PB board I have, and if it works just fine (which I'm pretty sure it does, I'll merge this commit.

BTW do you think it would be possible to do something similar to SPI/SPI1? It is different since each library actually contains two classes; SPIClass and SPISettings.

**Comment by MCUdude** [comment]
I connected SDA and SDA1 together, and SCL and SCL1 together on my 328PB board. I put together two simple sketches where Wire=master, Wire1=slave and the other sketch, Wire=slave, Wire1=master.

The weird this is that the sketch only works when Wire1=master and Wire=slave! I have no idea why. Can you look into it?

DOES WORK:
```c
// Send from Wire1 to Wire

#include <Wire.h>
#include <Wire1.h>

void setup()
{
  Wire1.begin(); // join i2c bus (address optional for master)
  Wire.begin(4);
  Wire.onReceive(receiveEvent);
  Serial.begin(9600);
  Serial.println("Wire1=master, Wire=slave");
}

byte x = 0;

void loop()
{
  Wire1.beginTransmission(4); // transmit to device #4
  Serial.println("1");
  Wire1.write("x is ");        // sends five bytes
  Wire1.write(x);              // sends one byte  
  Serial.println("2");
  Wire1.endTransmission();    // stop transmitting
  Serial.println("3");

  x++;
  delay(500);
}
```

DOES NOT WORK:
```c
// Send from Wire to Wire1

#include <Wire.h>
#include <Wire1.h>

void setup()
{
  Wire.begin();
  Wire1.begin(4);
  Wire1.onReceive(receiveEvent);
  Serial.begin(9600);
  Serial.println("Wire=master, Wire1=slave");
  delay(100);
}

byte x = 0;

void loop()
{
  Wire.beginTransmission(4);
  Serial.println("1");
  Wire.write("x is ");
  Wire.write(x);
  Serial.println("2");
  Wire.endTransmission();
  Serial.println("3");
  x++;
  delay(500);
}

void receiveEvent(int)
{
  while(1 < Wire1.available())
  {
    char c = Wire1.read();
    Serial.print(c);
  }
  int x = Wire1.read();
  Serial.println(x);
}
```

FYI the sketch above stops after it prints the number one. If I remove the physical connection between SDA+SDA1 and SCL+SCL1, the sketch runs again

**Comment by MCUdude** [comment]
@asukiaaa have you had the time to look into this?

**Comment by asukiaaa** [comment]
Thank you for checking.
I have a question.
Does this problem happen on [this branch](https://github.com/asukiaaa/MiniCore/tree/feature/define-wire2-with-using-twowire) but does not happen on master branch?

**Comment by MCUdude** [comment]
> Does this problem happen on this branch but does not happen on master branch?

A very reasonable question! Yes, it doe happen in the current Wire/Wire1 library too. I guess this must some kind of irrelevant issue because when I use Wire/Wire1 as master and slave separately, everything works fine. Do you have any idea what's going on?

Waiting for your reply. BTW this PR is pretty much ready to be merged!

**Comment by asukiaaa** [comment]
I checked the behavior with using the following program.
I got that Wire1 as slave and Wire as master cause this freezing as you mentioned.

By commenting out twi1.cpp step by step, I found that [setting TWCR1 with ack](https://github.com/MCUdude/MiniCore/blob/03599488039446ab30dc59f98696183d08d10311/avr/libraries/Wire1/src/utility/twi1.c#L357) causes blocking to print 2 on loop function.
However, I'm not sure how to solve the problem.
Do you have any idea?

```cpp
#include <Arduino.h>
#include <Wire.h>
#include <Wire1.h>

// Freezes
#define WIRE_SLAVE Wire1
#define WIRE_MASTER Wire

// No problem
// #define WIRE_SLAVE Wire
// #define WIRE_MASTER Wire1

#define DEVICE_ADDRESS 4

String slaveReceivedStr;

void receiveEvent(int) {
  slaveReceivedStr = "";
  while (0 < WIRE_SLAVE.available()) {
    slaveReceivedStr += (char) WIRE_SLAVE.read();
  }
}

void requestEvent() {
  WIRE_SLAVE.write(0);
}

void setup() {
  WIRE_MASTER.begin();
  WIRE_SLAVE.begin(DEVICE_ADDRESS);
  WIRE_SLAVE.onReceive(receiveEvent);
  WIRE_SLAVE.onRequest(requestEvent);
  Serial.begin(9600);
  Serial.println("Begin master and slave");
  delay(100);
}


void loop() {
  static byte x = 0;
  WIRE_MASTER.beginTransmission(DEVICE_ADDRESS);
  Serial.println("1");
  WIRE_MASTER.write("x is ");
  WIRE_MASTER.write(String(x).c_str());
  Serial.println("2");
  WIRE_MASTER.endTransmission();
  Serial.println("3");
  Serial.println("Slave received: " + slaveReceivedStr);
  ++x;
  delay(500);
}
```

**Comment by MCUdude** [comment]
I have no idea why this happens. Maybe this is an undocumented silicon bug? I've stumbled across silicon bugs on the ATmega324PB and 328PB before, particularly [this one](https://github.com/MCUdude/MiniCore/blob/58457b27ef52cf121d9997f226bf21799a33ad45/avr/cores/MCUdude_corefiles/wiring_analog.c#L210-L221).

The weird thing is that it works well as long as you don't connect TWI0 and TWI1 together. TWI0 works great as a master in regular applications. TWI1 works great as slave.

Do you think it has something to do with the two being physically connected together? Have you tried to connect it so that TWI0 is master and communicating with a separate board, and TWI1 is slave, and communicating with a different board?

**Comment by asukiaaa** [comment]
> I've stumbled across silicon bugs on the ATmega324PB and 328PB before, particularly this one.

How did you know the setting to avoid silicon bugs at that time?

> Have you tried to connect it so that TWI0 is master and communicating with a separate board, and TWI1 is slave, and communicating with a different board?

Yes I have
I use [LCD](https://github.com/asukiaaa/ST7032_asukiaaa) on Twi0 and be slave on Twi1.
The program is here.
https://github.com/asukiaaa/I2cControlPanel_asukiaaa/blob/master/examples/Firmware/Firmware.ino

By the way, how about to create an issue thread about this problem and merge this PR?
If you want to try codes before merge this, you can use it by checking out v2.0.6.

**Comment by MCUdude** [comment]
> By the way, how about to create an issue thread about this problem and merge this PR?
If you want to try codes before merge this, you can use it by checking out v2.0.6.

Sure, I'll merge it right away! Would you also like to create a PR for [MightyCore](https://github.com/MCUdude/MightyCore) as well? hardware-wise, the ATmega324PB is _very_ similar to ATmega328PB, so this library can be used there as well.

**Comment by asukiaaa** [comment]
Thank you for merging.

> Would you also like to create a PR for MightyCore as well?

I can create is but I cannot check it because I don't have device?
Could you copy Wire.h, Wire.cpp, Wire1.h and Wire1.cpp to the repository, check the behavior and merge (or commit)?

**Comment by asukiaaa** [comment]
Thank you for merging.

> Would you also like to create a PR for MightyCore as well?

I can create the PR but I cannot check it because I don't have device?
Could you copy Wire.h, Wire.cpp, Wire1.h and Wire1.cpp to the repository, check the behavior and merge (or commit)?

**Pull request merged**
