### PR TITLE
Add Boards Manager installation support for 2.0.1

### PR DESCRIPTION
**Pull request by per1234**
Temporary Boards Manager URL for testing:
https://raw.githubusercontent.com/per1234/MiniCore/bmtest/package_MCUdude_MiniCore_index.json

### CODE REVIEW

**Comment by MCUdude** [comment]
Awesome, thanks!

**Comment by per1234** [comment]
@MCUdude FYI, you titled the 2.0.1 release "MicroCore v2.0.1" rather than "MiniCore v2.0.1". Not really a big deal, but it could cause some confusion for someone and it's easy enough to edit the release notes.
clipboard01

**Comment by MCUdude** [comment]
Thanks for the heads-up! 

Have you received your MiniCore dev board yet?

**Comment by per1234** [comment]
Yes, thanks so much! I haven't had a chance to play with it much yet but there's someone on the forum having trouble with their ATmega328PB using the [watterott/ATmega328PB-Testing](https://github.com/watterott/ATmega328PB-Testing) core so I was planning on using it today to see if I can reproduce the problem and then see if it still occurs with MiniCore.

**Comment by per1234** [comment]
Here it is:
http://forum.arduino.cc/index.php?topic=544311

**Pull request merged**
