### PR TITLE
Update README.md to help fix Arduino as ISP issues

### PR DESCRIPTION
**Pull request by SimonMerrett**

### CODE REVIEW

**Comment by MCUdude** [comment]
Thanks! However 1.6.207 is actually a developer version. The latest IDE is bunded with 1.6.23, which also has this fixed I believe.

**Comment by SimonMerrett** [comment]
Interesting! I was using a recently downloaded Windows version of IDE 1.8.7 and although it probably came with 1.6.23 I went and installed 1.6.206, as per the MiniCore instructions (not noticing that I already had a newer version). The boards manager did not help as it doesn't recognise the order of the versions properly: 
image

**Comment by MCUdude** [comment]
I edited the readme a little more than a week ago. I no longer mention the install of 1.6.206, but rather refering to IDE 1.8.6 or newer.

**Comment by SimonMerrett** [comment]
No worries, I did read all instructions/documentation since Monday this week and I have no idea where I copied the 1.6.206 from (maybe a forum somewhere or some optiBoot documentation). I have posted my problem and fix on the Arduino forum so if you don't want to add in the clarification in my pull request, I can close it. Let me know.

**Comment by SimonMerrett** [comment]
https://forum.arduino.cc/index.php?topic=412070.msg3902489#msg3902489

**Comment by SimonMerrett** [comment]
Closed as no response either way.

**Comment by MCUdude** [comment]
I'm sorry, I totally forgot to reply. Yes, I think we can close this one. There's nothing wrong with MiniCore actually, but rather the Arduino as ISP code. Thanks for notifying me though! I'll keep this in mind when people are reporing issues with Arduino as ISP. However it's often best to get a dedicated programmer such as USBasp pr USBtinyISP.

**Pull request closed without merging**
